# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'coreML2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for coreML2

pod 'AWSS3'
pod 'AWSCognito'
pod 'AWSRekognition'
pod 'SwiftyJSON', '~> 4.0'
pod 'AlamofireSwiftyJSON'
pod "TPKeyboardAvoidingSwift"
pod 'AWSAPIGateway', '~> 2.4.7'

end
